# Generated by Django 2.1.5 on 2019-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20190320_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.TimeField(auto_now=True),
        ),
    ]
