# Generated by Django 2.1.5 on 2019-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
